USE [PianoLesson]
GO
/****** Object:  Table [dbo].[Lesson]    Script Date: 07-Nov-25 8:47:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Lesson](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](500) NULL,
 CONSTRAINT [PK_Lesson] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LessonPrerequisites]    Script Date: 07-Nov-25 8:47:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LessonPrerequisites](
	[IdLesson] [int] IDENTITY(1,1) NOT NULL,
	[PrerequisiteLessonId] [int] NOT NULL,
 CONSTRAINT [PK_LessonPrerequisites] PRIMARY KEY CLUSTERED 
(
	[IdLesson] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 07-Nov-25 8:47:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserLesson]    Script Date: 07-Nov-25 8:47:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserLesson](
	[IdUser] [int] IDENTITY(1,1) NOT NULL,
	[IdLesson] [int] NOT NULL,
	[IsCompleted] [bit] NOT NULL,
	[IsUnlocked] [bit] NOT NULL,
 CONSTRAINT [PK_UserLesson_1] PRIMARY KEY CLUSTERED 
(
	[IdUser] ASC,
	[IdLesson] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LessonPrerequisites]  WITH CHECK ADD  CONSTRAINT [FK_LessonPrerequisites_Lesson] FOREIGN KEY([IdLesson])
REFERENCES [dbo].[Lesson] ([Id])
GO
ALTER TABLE [dbo].[LessonPrerequisites] CHECK CONSTRAINT [FK_LessonPrerequisites_Lesson]
GO
ALTER TABLE [dbo].[UserLesson]  WITH CHECK ADD  CONSTRAINT [FK_UserLesson_Lesson1] FOREIGN KEY([IdLesson])
REFERENCES [dbo].[Lesson] ([Id])
GO
ALTER TABLE [dbo].[UserLesson] CHECK CONSTRAINT [FK_UserLesson_Lesson1]
GO
ALTER TABLE [dbo].[UserLesson]  WITH CHECK ADD  CONSTRAINT [FK_UserLesson_User] FOREIGN KEY([IdUser])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[UserLesson] CHECK CONSTRAINT [FK_UserLesson_User]
GO
USE [master]
GO
ALTER DATABASE [PianoLesson] SET  READ_WRITE 
GO
